package exception;
import java.util.InputMismatchException;
import java.util.Scanner;
public class throwexception {
	public static void main(String args[]) {
		try {
			showexception();
		}
		catch(ArithmeticException e) { 
			System.out.println("exception from different function");
		}
	}
	static void showexception() {
		try {
			Scanner sc=new Scanner(System.in);
			System.out.println("division operation");
			System.out.println("enter the numerator:");
			int num=sc.nextInt();
			System.out.println("enter the denominator:");
			int deno=sc.nextInt();
			int res=num/deno;
			System.out.println(res);
		}
		catch(ArithmeticException e) {
			throw e;
		}
	}
}
..............................
division operation
enter the numerator:
8
enter the denominator:
9
0
